server:  
  port: ${PORT:3333}

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 12
    leaseExpirationDurationInSeconds: 10
          
ribbon:
  eureka:
    enabled: true